### ISSUE TITLE
toBeEmpty yields false positives with self closing tags

### ISSUE THREAD

**Issue by jorgegonzalez** [gnapse/jest-dom#86] opened 2019-03-12 17:12 UTC
* `jest-dom` version: 3.1.2
* `node` version: 10.15.0
* `npm` (or `yarn`) version:  6.4.1 and 1.13.0

Relevant code or config

```javascript
expect(<div />).toBeEmpty(); // Fails
```

What you did:

Tried asserting that a React component would be empty based on certain props.

What happened:

Test fails with the following message:

```
expect(received).toBeEmpty()

Expected value to be empty received:
    <div />
```

Reproduction repository:

Problem description:

Suggested solution:

Not really sure but I’m open to looking into it.

**Comment by gnapse** [comment] 2019-03-12 20:16
@jorgegonzalez you're not supposed to pass React elements into `expect`. You have to pass actual DOM element references.

What `<div />` returns is not an actual `div` element. The expression `<div />` is roughly equivalent to `React.createElement('div', {}, null)` (that's more or less what it is transpired into by babel or something like that). But up to that point, no actual `div` still exists in the DOM. Only when you tell react to render that element (either via `ReactDOM.render` or in a test environment via `react-testing-library`'s `render` function) is that you get an actual `div` element. You then need to somehow grab a reference to the actual div element in the DOM, and that's what you test to check if it's empty or not.

Try this instead:

```js
const { container } = render(<div />);
expect(container.firstChild).toBeEmpty();
```

@kentcdodds since you're more into education, do you have any material to link to here that better explains the difference between react elements and DOM elements? I'm worried that my explanation above is not accurate enough.

**Comment by jorgegonzalez** [comment] 2019-03-12 20:59
Hi @gnapse thanks for the response. I was not clear enough in my original comment. I am using React and `react-testing-library`, and this is closer to the test that was failing for me: 

```js
const { container } = render(<div />);
expect(container).toBeEmpty();
```

That will throw the error I pasted above.

Changing it to `expect(container.firstChild).toBeEmpty();`) gives the following error:

`TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object`

**Comment by gnapse** [comment] 2019-03-13 12:26
Oh well, then it's up to what `<MyComponent />` renders. Once we're talking about a React component instead of a `div`, that component might well render lots of things. You render react components, but then you test on the DOM that a particular element is expected to be empty.

So yeah, we'd need to be able to see what `MyComponent` renders, in order to check what's the issue. I cannot reproduce because I have nothing to reproduce. I'll be closing this then.

**Closed by gnapse** 2019-03-13 12:26 UTC

**Comment by jorgegonzalez** [comment] 2019-03-13 13:28
Hmm `MyComponent />` is definitely rendering an empty `div`. Not sure why `expect(container.firstChild).toBeEmpty();)` fails.

**Comment by jorgegonzalez** [comment] 2019-03-13 13:40
Interestingly, this passes `expect(baseElement.firstChild.innerHTML).toBe('')`

**Comment by jorgegonzalez** [comment] 2019-03-13 13:44
I know why this is failing! I'm using `jest`extended` which has its own [`toBeEmpty()`](https://github.com/jest-community/jest-extended#tobeempty)  method.

**Comment by jorgegonzalez** [comment] 2019-03-13 14:21
In any case, thanks for helping me look into this.
