### ISSUE TITLE
toHaveStyle ignores hover styles

### ISSUE THREAD

**Issue by davidcai** [gnapse/jest-dom#59] opened 2018-09-18 20:35 UTC
### Describe the feature you'd like:

I have a button that displays different styles when mouse moves over it:

```css
background-color: green;
&:hover {
  background-color: red;
}
```

Here is my test:

```js
fireEvent.mouseOver(button);
expect(button).toHaveStyle(`
  background-color: red;
`);
```

However, the test complained that the background color is still green instead of red.
I tried `fireEvent.mouseEnter` before calling `mouseOver`. Didn't make any difference.

I don't think it is `fireEvent.mouseOver`'s problem. A onMouseOver event listener actually gets called when a mouseOver event is fired by `fireEvent`. Could it be a bug in jest-dom?

### Describe alternatives you've considered:

So far, I commented out all test that verify hover styles. And I probably should leave this style test to visual/browser test?

**Comment by gnapse** [comment] 2018-09-19 23:00
This is similar to #53, and I suspect that dom-testing-library's `fireEvent` merely takes care of calling the event handlers registered, but it does not have all the other real-life effects on the elements. I'm in the process of confirming this, and may open a ticket in dom-testing-library about this issue. Because if confirmed, this is something jest-dom cannot take care of, AFAICT.

**Comment by kentcdodds** [comment] 2018-09-19 23:08
I honestly don't think there's anything that dom-testing-library could reasonably do for this. I don't know if dispatching these events via JavaScript APIs in the browser would actually update the CSS applied. That'd be the first thing to check.

**Comment by gnapse** [comment] 2018-09-19 23:14
Yes, I think the same. It was not my intention to suggest that dom-testing-library should fix this. My point @davidcai is that `fireEvent.mouseOver` is not actually performing the changes in the dom that you're expecting it to.

**Comment by gnapse** [comment] 2018-10-03 20:05
This issue seems to be out of the scope of jest-dom, so I'm closing it. It can always be re-open if someone suggests an actionable path forward.

**Closed by gnapse** 2018-10-03 20:05 UTC

**Comment by muthuramakrishnan** [comment] 2022-12-26 16:18
It seems this issue isn't resolved with userEvent as well.
Here's the sandbox link: https://codesandbox.io/s/vibrant-hertz-qc128p?file=/src/App.test.js

As mentioned in the original issue, the test complained that the background color is still green instead of red.

version details
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^14.4.3",

**Comment by norayr93** [comment] 2023-01-30 10:45
I am encountering the same issue.Any updates on that ?

**Comment by theKashey** [comment] 2023-02-05 03:14
This is a limitation of a library below JSDOM - `nwsapi` the one [responsible for CSS](https://github.com/dperini/nwsapi/blob/master/src/nwsapi.js#L1093).

Long story short - the `:hover` selector will not be evaluated if document "currently" doesn't have any focused element, and later engine will use `doc.hoverElement` to understand which element is hovered, but such properly just does not exist.

**Comment by diana96alazzam** [comment] 2023-06-25 14:57
@theKashey Do you mean that it is impossible to test this scenario (where we have a component that has a div and a hidden button, when the user hover over the div, the button shows). I can test this scenario if I use `onMouseOver` and `onMouseOut` but I don't want the component state to change on each hover/un-hover. This is why I used `:hover` selector instead, but it is breaking my tests and I'm not sure if it is possible to keep same tests or not.

**Comment by theKashey** [comment] 2023-06-25 22:28
Try bumping `nwsapi`, the library responsible for this functionality - just remove the corresponding record from your lock file and install dependencies back. AFAIK the fix has been introduced back in May

**Comment by diana96alazzam** [comment] 2023-06-26 17:59
@theKashey Thanks for your reply!
I tried updating  `nwsapi`  to the latest version, but I'm still facing the same issue.
Can you help me and check if I'm doing something incorrectly?  [Code sandbox](https://codesandbox.io/p/github/diana96alazzam/test/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljd463vc000b356pbc8edksv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljd463vc000d356pkb4yk2i7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljd463vc000b356pbc8edksv%2522%253A%257B%2522id%2522%253A%2522cljd463vc000b356pbc8edksv%2522%252C%2522activeTabId%2522%253A%2522cljd482lb00p6356p3803eoeg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljd463va000a356pcn3q7j4s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252Fhide.test.tsx%2522%252C%2522id%2522%253A%2522cljd482lb00p6356p3803eoeg%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522cljd463vc000d356pkb4yk2i7%2522%253A%257B%2522id%2522%253A%2522cljd463vc000d356pkb4yk2i7%2522%252C%2522activeTabId%2522%253A%2522cljd47sb400mc356pw2bwn7cs%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cljd46u1c00dj356p9p0x1xp6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljd46zbj00hz356pyncmngbl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522cljd47sb400mc356pw2bwn7cs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljd47t9s000qfpjr5qh9gl3g%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by theKashey** [comment] 2023-06-27 07:18
Look like the fix got reverted as long as it caused regression and hasn't been implemented back - https://github.com/dperini/nwsapi/issues/80

**Comment by thatPranav** [comment] 2023-08-31 09:55
https://stackoverflow.com/a/65196078/7422491
